apiVersion: batch/v1
kind: Job
metadata:
  name: seed-todos-db
spec:
  template:
    spec:
      containers:
        - name: psql
          image: postgres:16
          command: ["sh", "-c", "psql -h postgres-service -U postgres -f /seed/todos_db.sql"]
          env:
            - name: PGPASSWORD
              value: "postgres"
          volumeMounts:
            - name: seed-sql
              mountPath: /seed
      volumes:
        - name: seed-sql
          configMap:
            name: todos-seed-sql
      restartPolicy: OnFailure
